[[redirects]]
  from = "/api/*"
  to = "https://nodejs314.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/uploads/*"
  to = "https://nodejs314.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}